name: Build NixOS-Installers

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write   # GHCR
  id-token: write

jobs:
  build-all:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # -------------------------
      # Install Nix
      # -------------------------
      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            keep-outputs = true
            keep-derivations = true
      # =========================
      # 1️⃣NETBOOT
      # =========================
      - name: Build Netboot
        run: |
          set -euxo pipefail
          nix build .#netboot -o netboot-result
          mkdir -p netboot-artifacts
          cp -L -r netboot-result/* netboot-artifacts/

      # =========================
      # ISO
      # =========================
      - name: Build Installer ISO
        run: |
          set -euxo pipefail
          nix build .#iso-installer -o iso-result
          sudo cp -L iso-result/iso/*.iso nixos-installer.iso

      # =========================
      # Create tag
      # =========================
      - name: Generate Tag
        id: tag
        run: |
          TAG="v1.0.${{ github.run_number }}"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      # =========================
      # Patch netboot.ipxe
      # =========================
      - name: Fix netboot.ipxe for release assets
        run: |
          set -euxo pipefail

          BASE="https://github.com/${{ github.repository }}/releases/download/${{ steps.tag.outputs.tag }}"

          FILE="netboot-artifacts/netboot.ipxe"

          # Insert imgfree if not already present
          grep -q '^imgfree' "$FILE" || sed -i '2i imgfree' "$FILE"

          # Replace only the file paths, keep params untouched
          sed -i -E "s|^kernel[[:space:]]+.*bzImage|kernel $BASE/bzImage|" "$FILE"
          sed -i -E "s|^initrd[[:space:]]+.*initrd|initrd $BASE/initrd|" "$FILE"

      # =========================
      # Create release
      # =========================
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: Release ${{ steps.tag.outputs.tag }}
          body: |
            NixOS build outputs:
            - Installer ISO
            - Netboot artifacts
          files: |
            nixos-installer.iso
            netboot-artifacts/netboot.ipxe
            netboot-artifacts/initrd
            netboot-artifacts/bzImage
          latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

